name: flutter_supabase_template
description: Example of a flutter application to use Very Good CLI and Supabase
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  email_launcher:
    path: packages/email_launcher
  equatable: ^2.0.5
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  go_router: ^6.5.6
  intl: ^0.17.0
  mockingjay: ^0.3.0
  mocktail_image_network: ^0.3.1
  supabase_auth_client:
    path: packages/supabase_auth_client
  supabase_database_client:
    path: packages/supabase_database_client
  supabase_flutter: ^1.7.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  build_verify: ^3.1.0
  flutter_gen_runner: ^5.3.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.2.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/.env

flutter_gen:
  integrations:
    flutter_svg: true
